services:
    app.form_login_authenticator:
        class: Xtraball\UserBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder", "@security.csrf.token_manager"]
    user_bundle.role_manager.default:
        class: Xtraball\UserBundle\Model\RoleManager
        arguments: ['@doctrine', '%user_bundle.role_class%']
    xtraball.user_bundle:
        class: Xtraball\UserBundle\Security\RoleHierarchy
        public: false
        arguments: ['@user_bundle.role_manager']
    xtraball.user_bundle_voter:
        class: Xtraball\UserBundle\Security\RoleHierarchyVoter
        public: false
        tags:
            - { name: security.voter, priority: 240 }
        arguments: ['@xtraball.user_bundle']